#!/bin/sh
case "$1" in
  start)
    echo "Levantando Sambac"
    mkdir -p /var/log/samba
    # Lanzar los binarios que AD DC instaló
    /usr/sbin/smbd -D
    /usr/sbin/nmbd -D
    ;;
  stop)
    killall smbd nmbd
    ;;
esac