#!/bin/sh

case "$1" in
  start)
    echo "Iniciando Servidor Seguro"
    
    # 1. Crear directorio si no existe
    mkdir -p /storage
    
    # 2. Generar certificados SSL automáticos (solo si no existen)
    if [ ! -f /etc/ssl/server.crt ]; then
        mkdir -p /etc/ssl
        openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/server.key \
        -out /etc/ssl/server.crt -days 365 -nodes \
        -subj "/C=ES/ST=Gamer/L=Local/O=SalvaOS/CN=salva-pc"
    fi

    # 3. Lanzar servidor OpenSSL en segundo plano exponiendo /storage
    # Usamos '&' para que BusyBox no se quede bloqueado esperando
    (cd /storage && openssl s_server -accept 443 -cert /etc/ssl/server.crt -key /etc/ssl/server.key -WWW) &
    
    # 4. Mostrar la IP en pantalla para saber cómo conectar
    echo "Servidor listo en: https://$(ip route get 1.2.3.4 | awk '{print $7}')"
    ;;
  stop)
    killall openssl
    ;;
  *)
    echo "Uso: $0 {start|stop}"
    exit 1
    ;;
esac